### ISSUE TITLE
GeneralImprovements BetterMonitor Config Incompatibility

### ISSUE THREAD

**Issue by CommanderSlav** [TheDeadSnake/LC-Touchscreen#18] opened 2024-01-29 06:50 UTC
When enabling BetterMonitors, the option for changing the camera via the button doesn't want to work because of some weird overlap when standing in front of the screen, however if you crouch in front of it, the switch camera button, you're able to - It seems to be related to the following, it's as if the screen is that is the "touch screen" is in the middle of the 2 monitors on the left side (far left and middle). So it covers up the buttons 

I did notice that if you click on the far left screen as if the middle screen was shifted over, it does function but it's like the screen moved

Makes it unusable

**Comment by TheDeadSnake** [comment] 2024-01-29 17:02
Do you have any other plugins installed or any other information ?
With just BepInEx, TouchScreen and BetterMonitor installed I'm unable to replicate the issue.

**Comment by PickeBlind** [comment] 2024-01-29 18:39
He was likely referring to the UseBetterMonitors config option of GeneralImprovements, which "uses 12 fully customizable and integrated monitors instead of the 8 vanilla ones with overlays). I've recreated the issue with only GI (with the config option enabled), Touchscreen v1.0.8 and BepInEx installed. Will test with the newest version of Touchscreen when it gets to r2modman.

![image](https://github.com/TheDeadSnake/LC-Touchscreen/assets/28679388/ba88a0d9-7328-47af-b7f3-8f9dc764806a)
![image](https://github.com/TheDeadSnake/LC-Touchscreen/assets/28679388/09d04454-774e-460a-a073-1a12a0c85e6a)

I apologize if this has already been fixed in v1.0.9

**Comment by TheDeadSnake** [comment] 2024-01-29 18:54
It'll not be fixed in v1.0.9, as I could not reproduce the issue. In the next update two other issues were fixed.

**Comment by NilaierMusic** [comment] 2024-01-29 20:56
> It'll not be fixed in v1.0.9, as I could not reproduce the issue. In the next update two other issues were fixed.

So, what you need to reproduce this bug. Have the latest versions of both mods installed. Enable `UseBetterMonitors` in [GeneralImprovements](https://github.com/Shaosil/LethalCompanyMods-GeneralImprovements) config file. After that, get into the game. Launch the ship and go towards the monitor. You will see that Touchscreen's hitbox/collision box got shifted between the new big monitor from GeneralImprovements and old, vanilla map monitor.

Here's a video to showcase that (crappy due to Github's 10 mb video limit):

https://github.com/TheDeadSnake/LC-Touchscreen/assets/86863646/244cfac8-385a-4ad9-b3d7-7de4368f078f

**Comment by TheDeadSnake** [comment] 2024-01-29 22:49
Fixed in v1.0.10

**Closed as completed by TheDeadSnake** 2024-01-29 22:49 UTC
Labels: bug, compatibility
