### ISSUE TITLE
My cursor not true

### ISSUE THREAD

**Issue by MGevze** [TheDeadSnake/LC-Touchscreen#24] opened 2024-02-21 21:39 UTC
Hello, I use this mod. It works pretty well but in screen, my cursor is just a square. I don't know why. Please can someone help? I paste the png files in BepinEx/plugins folder. Also TouchScreen.dll

**Comment by TheDeadSnake** [comment] 2024-02-21 22:19
Duplicate of #11, #6 and #1.
For the 'White box cursor', please refer to the [Wiki](https://github.com/TheDeadSnake/LC-Touchscreen/wiki/Known-issues) in the first place. However, should the issue persist please re-open the issue.

**Closed as completed by TheDeadSnake** 2024-02-21 22:19 UTC
