### ISSUE TITLE
[Spoilers] v50 Compatibility

### ISSUE THREAD

**Issue by vermilionshadow-vk** [TheDeadSnake/LC-Touchscreen#28] opened 2024-04-05 05:05 UTC
Wanted to give a heads up that the patch for v50 beta 3 added a new interior trap.
Currently, Touchscreen is unable to temporarily deactivate this trap (it can still deactivate Mines & Turrets).

**Comment by TheDeadSnake** [comment] 2024-04-06 16:23
Thank you for the heads-up.
I did not take a look at the new v50 content yet, however if the trap can be disabled via the Terminal the issue is most likely in the [OnPlayerInteraction](https://github.com/TheDeadSnake/LC-Touchscreen/blob/3f23c7bcaba1f71df9dff468c24719fde5aafc43/ScreenScript.cs#L57) function of ScreenScript.cs.
~~If v50 is fully released by then and LeathalAPI.GameLibs is updated I can push it in the next update (v1.1.1).~~

**Comment by mariusvn** [comment] 2024-04-15 17:01
v50 is now release ;)

**Comment by TheDeadSnake** [comment] 2024-04-16 14:22
Jep, right now I'm waiting for [LethalAPI.GameLibs](https://www.nuget.org/packages/LethalAPI.GameLibs) to update. If it isn't updated by Friday, I will do it myself and try to release v1.1.2 the same day.

**Comment by TheDeadSnake** [comment] 2024-04-19 21:01
Fixed in v1.1.2

**Closed as completed by TheDeadSnake** 2024-04-19 21:01 UTC
Labels: compatibility
